# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-epigen-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - conda-forge::r-markdown=1.1
  - conda-forge::r-base=3.6.1
  - conda-forge::r-dplyr=1.0.0
  - conda-forge::r-tidyr=1.1.0
  - conda-forge::r-stringr=1.4.0
  - conda-forge::r-lubridate=1.7.9
  - conda-forge::r-readr=1.3.1
