name: nf-core branch protection
# This workflow is triggered on PRs to master branch on the repository
# It fails when someone tries to make a PR against the nf-core `master` branch instead of `dev`
on:
  pull_request:
    branches: [master]

jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      # PRs to the nf-core repo master branch are only ok if coming from the nf-core repo `dev` or any `patch` branches
      - name: Check PRs
        if: github.repository == 'czbiohub/nf-epigen'
        run: |
          { [[ $(git remote get-url origin) == "*czbiohub/nf-epigen" ]] && [[ $GITHUB_HEAD_REF = "dev" ]]; } || [[ $GITHUB_HEAD_REF == "patch" ]]
